### PR TITLE
[DAF-4116] reset position when update new datasource

### PR DESCRIPTION
**Pull request by ghost**
Sometimes the `BetterPlayerController` will return the position of the old datasource, so I reset the `_seekposition` before setting a new data source to avoid that.

### CODE REVIEW

**Review by mvn-thanhluu-hn — APPROVED** [review]
LGTM.

**Comment by mvn-thanhluu-hn** [comment]
@mvn-datnguyen-hn 
Sorry, I forgot. This fix is needed for `pip` first so please change target branch to `feature/pip` or create new PR.

**Comment by ghost** [comment]
@mvn-thanhluu-hn thanks, I updated branch

**Review by noboru-i — APPROVED** [review]
LGTM.

@HiroshiOshiro 
PIP周りのチケットなので、認識しておいていただければと思います。

**Pull request merged**
